version: '3.8'

services:
  quick_docs_helper:
    build: .
    container_name: quick_docs_helper_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
