from pydantic import BaseModel

class LyLichData(BaseModel):
    """Schema chứa dữ liệu tờ khai Lý lịch cá nhân"""
    ho_ten: str = ""
    gioi_tinh: str = ""
    ngay_sinh: str = ""
    thang_sinh: str = ""
    nam_sinh: str = ""
    noi_sinh: str = ""
    que_quan: str = ""
    quoc_tich: str = ""
    dan_toc: str = ""
    ton_giao: str = ""
    cccd: str = ""
    ngay_cccd: str = ""
    thang_cccd: str = ""
    nam_cccd: str = ""
    noi_cap_cccd: str = ""
    hoc_van: str = ""
    nghe_nghiep: str = ""
    noi_lam_viec: str = ""
    noi_thuong_tru: str = ""
    noi_tam_tru: str = ""
    noi_o_hien_tai: str = ""
    chuc_vu: str = ""
    doan_the: str = ""
